name: "HotCI"
description: ""
inputs:
  from-tag:
    description: "Tag from which to upgrade"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Get Release Name
      working-directory: .
      run: |
        RELNAME=$(${{ github.action_path }}/scripts/get_release_name ./rebar.config)
        echo "RELNAME=$RELNAME" >> $GITHUB_ENV
      shell: bash

    - name: Set The From Version Tag
      run: |
        if [ -n "$INPUT_FROM_TAG" ]; then
          echo "FROM_TAG=$INPUT_FROM_TAG" >> $GITHUB_ENV
        else
          FROM_TAG=$(git tag -l --sort=committerdate '*.*.*' | tail -n 1)
          echo "::debug::FROM_TAG: $FROM_TAG"
          echo "FROM_TAG=$FROM_TAG" >> $GITHUB_ENV
        fi
      shell: bash
      env:
        INPUT_FROM_TAG: ${{ inputs.from-tag }}
    
    - name: Check From Tag
      if: ${{ env.FROM_TAG == '' }}
      run: |
        echo "::error title=Invalid From Tag::There is either no version tag in this repository or the from-tag parameter is blank."
        exit 1
      shell: bash

    - name: Run validation checks and build releases
      working-directory: .
      run: |
        ${{ github.action_path }}/scripts/check_versions ${{ env.RELNAME }} $(/usr/bin/git log -1 --format='%H') ${{ env.FROM_TAG }} > vsn.log
        cat vsn.log
        cat vsn.log | awk '/Generated appup/ || /Compiling .*\.appup\.src/ { appup=1 }
                           /relup successfully created!/ { relup=1 }
                           END { if (!appup) { echo "::error title=Missing appup"; exit 1 }
                                 if (!relup) { echo "::error title=Missing relup"; exit 1} }'
        OLD=$(cat vsn.log | awk '/OLD:/ {print $2}')
        NEW=$(cat vsn.log | awk '/NEW:/ {print $2}')

        echo "OLD_TAR=$OLD" >> $GITHUB_ENV
        echo "NEW_TAR=$NEW" >> $GITHUB_ENV
      shell: bash

    - name: Test upgrade and downgrade of the application
      working-directory: .
      run: |
        BASE_DIR="${{ runner.temp }}/.hotci"
        mkdir $BASE_DIR

        RELEASES_DIR="$BASE_DIR/releases"
        mkdir $RELEASES_DIR
        cp "${{ env.OLD_TAR }}" $RELEASES_DIR
        cp "${{ env.NEW_TAR }}" $RELEASES_DIR

        OLD_TAG=$(echo "${{ env.OLD_TAR }}" | sed -nr 's/^.*\/\${{ env.RELNAME }}-(.+)\.tar\.gz$/\1/p')
        NEW_TAG=$(echo "${{ env.NEW_TAR }}" | sed -nr 's/^.*\/\${{ env.RELNAME }}-(.+)\.tar\.gz$/\1/p')

        CONFIG_DIR="$BASE_DIR/config"
        mkdir $CONFIG_DIR
        echo -e "{old_version, \"$OLD_TAG\"}.\n{new_version, \"$NEW_TAG\"}.\n{release_name, \"${{ env.RELNAME }}\"}.\n{release_dir, \"$RELEASES_DIR\"}." >> $CONFIG_DIR/config.config

        RESULTS_DIR="$BASE_DIR/results"
        mkdir $RESULTS_DIR
        rebar3 as hotci ct --config $CONFIG_DIR/config.config --logdir $RESULTS_DIR
      shell: bash
