name: Publish CT Results
description: Publish and Upload CT results as artifact

inputs:
  test-name:
    description: Name of the test suite
    required: true
    default: Some test
  
runs:
  using: composite
  steps:
  - name: Upload test results as artifact
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.test-name }}
      path: ./results
      compression-level: 9
      retention-days: 30
  
  - name: Publish test results
    uses: EnricoMi/publish-unit-test-result-action@v2
    with:
      check_name: ${{ inputs.test-name }}
      files: |
        ./results/**/*.xml