#!/usr/bin/env escript
-module(check_versions).
-mode(compile).

usage() ->
    io:format("usage: Relname Branch Version\n"),
    halt(1).

main([Relname]) ->
    main([Relname, os:cmd("git rev-parse --abbrev-ref HEAD")]);

main([Relname, Branch]) ->
    "v"++_LastVsn = LastTag = string:trim(os:cmd("git tag -l --sort=committerdate 'v*.*.*' | tail -n 1")),
    main([Relname, Branch, LastTag]);

main([Relname, Branch, PrevTag]) ->
    SrcPrefix = "apps/",
    
    io:format("switching to ~ts and back to ~ts~n", [PrevTag, Branch]),
    io:format("~p: ~ts~n", [?LINE, os:cmd("git checkout "++PrevTag)]),
    io:format("~p: ~ts~n", [?LINE, os:cmd("rebar3 do clean -a, release, tar")]),
    io:format("~p: ~ts~n", [?LINE, os:cmd("git checkout "++Branch)]),
    io:format("~p: ~ts~n", [?LINE, os:cmd("rebar3 do clean -a, release")]),
    RelFiles = filelib:wildcard("_build/default/rel/*/releases/**/*.rel"),
    case length(RelFiles) of
        2 ->
            ok;
        N ->
            io:format("Expected to find two releases, found ~p~n"
                      "The current release likely has the same version as "
                      "an older one.~n"
                      "Bump up the release version to generate relups.~n",
                      [N]),
            init:stop(1)
    end,
    Releases = [Content || Path <- RelFiles,
                           {ok, [Content]} <- [file:consult(Path)]],

    ChangedFiles = [Sub
                    || Path <- diff_lines(os:cmd("git diff "++PrevTag)),
                       Sub <- [string:prefix(Path, SrcPrefix)],
                       Sub =/= nomatch],
    AppsChanged = [list_to_atom(App) ||
                   App <- lists:usort([hd(filename:split(Name)) || Name <- ChangedFiles])],
    [{_, OldStr, Old}, {_, NewStr, New}] = lists:sort(
        [{to_vsn(VsnStr), VsnStr, Apps}
         || {release, {_Name, VsnStr}, _ERTS, Apps} <- Releases]
    ),
    Incorrect = lists:filter(
        fun(App) ->
            OldVsn = case lists:keyfind(App, 1, Old) of
                {_, Vsn} -> Vsn;
                false -> ""
            end,                
            {_, NewVsn} = lists:keyfind(App, 1, New),
            OldVsn == NewVsn
        end,
        AppsChanged
    ),
    case Incorrect of
        [] ->
            ok;
        _ ->
            io:format("Applications have changes applied and need a "
                      "version bump: ~p~n", [Incorrect]),
            init:stop(1)
    end,
    %% Build relup phase
    io:format("~ts~n", [os:cmd("rebar3 appup generate")]),
    io:format("~ts~n", [os:cmd("rebar3 relup -n"++ Relname ++" -v "++NewStr++" -u "++OldStr)]),
    io:format("~ts~n", [os:cmd("rebar3 tar")]),
    io:format("OLD: _build/default/rel/"++Relname++"/"++Relname++"-~ts.tar.gz~n"
              "NEW: _build/default/rel/"++Relname++"/"++Relname++"-~ts.tar.gz~n",
              [OldStr, NewStr]),
    init:stop(0);

main(_) ->
    usage().

to_vsn(Str) ->
    [Restart, Relup, Reload] = [list_to_integer(S) || S <- string:lexemes(Str, ".")],
    {Restart, Relup, Reload}.

diff_lines(Str) ->
    [string:sub_string(Path, 3)
     || Line <- string:lexemes(Str, "\n"),
        nomatch =/= string:prefix(Line, "+++") orelse
        nomatch =/= string:prefix(Line, "---"),
        [_, Path |_ ] <- [string:lexemes(Line, " ")]
    ].